services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile.backend
    ports:
      - "3001:3001"
    depends_on:
      - redis
      - mongodb
    env_file:
      - .env
    working_dir: /app/backend
    command: ["npm", "start"]
    restart: always  

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile.frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    working_dir: /app/frontend
    command: ["npm", "run", "start"]
    restart: always  

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always  

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always  

volumes:
  mongo_data:
