name: Monorepo CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  setup:
    name: Setup and Install Dependencies
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies for all workspaces
        run: npm install --workspaces

  test:
    name: Run Tests with Turbo
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies for all workspaces
        run: npm install --workspaces

      - name: Run Tests with Turbo
        env:
          REDIS_HOST: 127.0.0.1
          REDIS_PORT: 6379
          MONGO_URI: mongodb://127.0.0.1:27017/testdb
        run: npx turbo run test --no-cache

  build:
    name: Build All Projects with Turbo
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies for all workspaces
        run: npm install --workspaces

      - name: Build Projects with Turbo
        run: npx turbo run build --no-cache
