name: Monorepo CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  setup:
    name: Setup and Install Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies for all workspaces
        run: npm install --workspaces

  test:
    name: Run Tests with Turbo
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies for all workspaces
        run: npm install --workspaces

      - name: Run Tests with Turbo
        run: npx turbo run test --no-cache

  build:
    name: Build All Projects with Turbo
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies for all workspaces
        run: npm install --workspaces

      - name: Build Projects with Turbo
        run: npx turbo run build --no-cache
